version: '3.8'

services:

  mysql:
    image: mysql:8

    container_name: fifa_mysql

    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fifa_db

    ports:
      - '3307:3306'

    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: ./backend

    container_name: fifa_backend

    restart: always

    ports:
      - '3000:3000'

    depends_on:
      - mysql

    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: fifa_db
      GROQ_API_KEY: ${GROQ_API_KEY}
      JWT_SECRET: ${JWT_SECRET}

  frontend:
    build: ./frontend

    container_name: fifa_frontend

    restart: always

    ports:
      - '4200:4200'

    depends_on:
      - backend

volumes:
  mysql_data: